
package justtalk.demo.model; 

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "videos")
public class Video {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long videoId;          // every video has a unique ID -> use to post, get from digital ocean CDN
    
    @Column(nullable = false)
    private Long sessionId;

    @Column(nullable = false)
    private String title;           // video name, autogenerated if not given

    @Column(nullable = false)
    private LocalDateTime createdAt; // time of creation

    @Column(nullable = false)
    private String link;
}